mod shared;
#[allow(unused_imports)]
use shared::*;

use ahash::AHashSet;
use alphabet_detector::Language::*;
use alphabet_detector::*;
use rstest::*;

#[rstest(expected_language, word,
    case(Czech, "subjektů"),
    case(Esperanto, "apenaŭ"),
    case(Esperanto, "intermiksiĝis"),
    case(Esperanto, "kreitaĵoj"),
    case(Esperanto, "monaĥinoj"),
    case(Esperanto, "nesufiĉecon"),
    case(Esperanto, "ŝpinante"),
    case(German, "groß"),
    case(Greek, "σχέδια"),
    case(Hungarian, "fekvő"),
    case(Hungarian, "meggyűrűzni"),
    case(Icelandic, "þagnarskyldu"),
    case(Japanese, "ヴェダイヤモンド"),
    case(Kazakh, "ақын"),
    case(Kazakh, "шұрайлы"),
    case(Lithuanian, "įrengus"),
    case(Lithuanian, "mergelės"),
    case(Lithuanian, "slegiamų"),
    case(Macedonian, "ќерка"),
    case(Macedonian, "припаѓа"),
    case(Polish, "budowę"),
    case(Polish, "groźne"),
    case(Polish, "mniejszości"),
    case(Polish, "państwowych"),
    case(Polish, "wystąpią"),
    case(Romanian, "ialomiţa"),
    case(Serbian, "наслеђивања"),
    case(Serbian, "неисквареношћу"),
    case(Slovak, "mŕtvych"),
    case(Slovak, "podĺa"),
    case(Slovak, "pohľade"),
    case(Ukrainian, "ґрунтовому"),
    case(Ukrainian, "пропонує"),
    case(Vietnamese, "biểu"),
    case(Vietnamese, "bỡi"),
    case(Vietnamese, "cằm"),
    case(Vietnamese, "chẳng"),
    case(Vietnamese, "chất"),
    case(Vietnamese, "chỉnh"),
    case(Vietnamese, "chức"),
    case(Vietnamese, "của"),
    case(Vietnamese, "đạp"),
    case(Vietnamese, "dắt"),
    case(Vietnamese, "diễm"),
    case(Vietnamese, "giới"),
    case(Vietnamese, "hậu"),
    case(Vietnamese, "hiền"),
    case(Vietnamese, "hợp"),
    case(Vietnamese, "hưng"),
    case(Vietnamese, "kỳ"),
    case(Vietnamese, "kỷ"),
    case(Vietnamese, "lẻn"),
    case(Vietnamese, "mặn"),
    case(Vietnamese, "mỗi"),
    case(Vietnamese, "một"),
    case(Vietnamese, "mỵ"),
    case(Vietnamese, "nguồn"),
    case(Vietnamese, "nhẫn"),
    case(Vietnamese, "nhở"),
    case(Vietnamese, "những"),
    case(Vietnamese, "phế"),
    case(Vietnamese, "quẩy"),
    case(Vietnamese, "sẵn"),
    case(Vietnamese, "sỏi"),
    case(Vietnamese, "sử"),
    case(Vietnamese, "thần"),
    case(Vietnamese, "thơ"),
    case(Vietnamese, "thờ"),
    case(Vietnamese, "thực"),
    case(Vietnamese, "tổng"),
    case(Vietnamese, "tốt"),
    case(Vietnamese, "từng"),
    case(Vietnamese, "việc"),
    case(Yoruba, "aṣiwèrè"),
    case(Yoruba, "ṣaaju"),

    // unique script
    case(Armenian, "ունենա"),
    case(Georgian, "გარეუბან"),
    case(Greek, "σταμάτησε"),
    case(Gujarati, "ઉપકરણોની"),
    case(Japanese, "びさ"),
    case(Korean, "대결구도가"),
    case(PunjabiEastern, "ਮੋਟਰਸਾਈਕਲਾਂ"),
    case(Tamil, "துன்பங்களை"),
    case(Telugu, "కృష్ణదేవరాయలు"),
    case(Thai, "ในทางหลวงหมายเลข"),
)]
fn test_word_uniq(expected_language: Language, word: &str) {
    let found_words: Vec<_> = alphabet_detector::from_ch_iter(word.char_indices()).collect();
    if found_words.len() > 1 {
        panic!("Not a word: {} got: {:?}", word, found_words);
    }
    let languages = langs_count_max(found_words[0].langs_cnt).0;

    assert!(
        languages.len() == 1,
        "{:?} word '{}', got {:?}",
        expected_language,
        word,
        languages
    );

    let language = languages.iter().next().copied().unwrap();
    assert_eq!(
        language, expected_language,
        "word '{}', got {:?}",
        word, languages
    );
}

#[rstest(expected_language, word, expected_languages,
    case::eng_like(Slovak, "šefčovič's", ahashset!(Bosnian, Croatian, Czech, Latgalian, Latvian, Lithuanian, Silesian, Slovak, Slovene)),
    case(AlbanianTosk, "hashemidëve", ahashset!(Afrikaans, AlbanianTosk, AymaraCentral, Catalan, Dutch, French, Limburgish, Luxembourgish)),
    case(Arabic, "والموضوع", ahashset!(AcehneseJawi, Arabic, ArabicEgyptian, ArabicMesopotamian, ArabicMoroccan, ArabicNajdi, ArabicNorthLevantine, ArabicSouthernYemeni, ArabicSouthLevantine, ArabicTunisian, AzerbaijaniSouth, BanjarJawi, Dari, DogriPersoArabic, KanuriCentralAjami, Kashmiri, KurdishCentral, KurdishSouthern, Pashto, PastoSouthern, Persian, PersianWestern, PunjabiEasternShahmukhi, Sindhi, Urdu, Uyghur)),
    case(AzerbaijaniNorth, "məhərrəm", ahashset!(AzerbaijaniNorth, TatarCrimean)),
    case(Belarusian, "павінен", ahashset!(Belarusian, Kazakh, Ukrainian)),
    case(Belarusian, "раскрывае", ahashset!(Bashkir, Belarusian, Kazakh, Kyrgyz, MongolianHalh, Russian, Tatar)),
    case(Bengali, "জানাতে", ahashset!(Assamese, Bengali, BishnupriyaManipuri, Meitei)),
    case(Bulgarian, "довършат", ahashset!(Bashkir, Bulgarian, Kazakh, Kyrgyz, MongolianHalh, OldChurchSlavonic, Russian, Tajik, Tatar)),
    case(Bulgarian, "плаваща", ahashset!(Bashkir, Bulgarian, Kazakh, Kyrgyz, MongolianHalh, OldChurchSlavonic, Russian, Tatar, Ukrainian)),
    case(Catalan, "contradicció", ahashset!(Afrikaans, Asturian, AymaraCentral, Catalan, Czech, Dutch, Fon, Galician, Guarani, Hungarian, Igbo, Irish, Kabuverdianu, Limburgish, Lombard, Luxembourgish, Occitan, Papiamento, Polish, Portuguese, Sardinian, Shona, Sicilian, Slovak, Spanish, Venetian, Vietnamese, Welsh)),
    case(Catalan, "només", ahashset!(Acehnese, Afrikaans, Asturian, AymaraCentral, Balinese, Bambara, Banjar, Basque, Bokmal, Catalan, CreoleHaitian, Czech, Danish, Dutch, Ewe, Fon, French, Galician, Guarani, Hungarian, Icelandic, Igbo, Ilocano, Irish, Italian, Kabuverdianu, Ligurian, Limburgish, Lombard, Luxembourgish, Occitan, Papiamento, Portuguese, Sardinian, Shona, Sicilian, Slovak, Spanish, Venetian, Vietnamese, Waray, Welsh, Yoruba)),
    case(Catalan, "pràctiques", ahashset!(Catalan, French, Italian, Portuguese, Sardinian, Sicilian, Venetian, Vietnamese)),
    case(Catalan, "substituïts", ahashset!(Afrikaans, AymaraCentral, Catalan, Dutch, French, Welsh)),
    case(Croatian, "nađete", ahashset!(Bosnian, Croatian, Vietnamese)),
    case(Croatian, "prihvaćanju", ahashset!(Bosnian, Croatian)),
    case(Czech, "jeďte", ahashset!(Czech, Slovak)),
    case(Czech, "navržen", ahashset!(Bosnian, Croatian, Czech, Estonian, Latgalian, Latvian, Lithuanian, Silesian, Slovak, Slovene)),
    case(Czech, "rozdělit", ahashset!(Czech, Fon)),
    case(Czech, "rtuť", ahashset!(Czech, Slovak)),
    case(Czech, "tvořen", ahashset!(Czech, Silesian)),
    case(Czech, "vývoj", ahashset!(Afrikaans, Czech, Faroese, Guarani, Icelandic, Slovak)),
    case(Czech, "zaručen", ahashset!(Bosnian, Croatian, Czech, Kabyle, Latgalian, Latvian, Lithuanian, Silesian, Slovak, Slovene)),
    case(Czech, "zkouškou", ahashset!(Bosnian, Croatian, Czech, Estonian, Latgalian, Latvian, Lithuanian, Sepedi, Sesotho, Silesian, Slovak, Slovene)),
    case(Danish, "direktør", ahashset!(Bokmal, Czech, Danish, Faroese, Nynorsk)),
    case(Danish, "indebærer", ahashset!(Bokmal, Danish, Faroese, French, Icelandic, Latin, Nynorsk)),
    case(Danish, "måned", ahashset!(Bokmal, Danish, Nynorsk, Swedish)),
    case(English, "house", ahashset!(Acehnese, Afrikaans, AlbanianTosk, Asturian, AymaraCentral, AzerbaijaniNorth, Balinese, Bambara, Banjar, Basque, Bemba, Bokmal, Bosnian, Buginese, Catalan, Cebuano, Chokwe, CreoleHaitian, Croatian, Czech, Danish, Dutch, Dyula, English, Esperanto, Estonian, Ewe, Faroese, Finnish, Fon, French, Friulian, FulfuldeNigerian, GaelicScottish, Galician, Ganda, German, Guarani, Hausa, Hungarian, Icelandic, Igbo, Indonesian, Irish, Italian, Javanese, Jingpho, Kabiye, Kabuverdianu, Kabyle, Kamba, KanuriCentral, Kikongo, Kikuyu, Kimbundu, Kinyarwanda, KurdishNorthern, Latgalian, Latin, Latvian, Ligurian, Limburgish, Lingala, Lithuanian, Lombard, LubaKasai, Luo, Luxembourgish, Malay, Maltese, Minangkabau, Mizo, Mossi, Nuer, Nyanja, Nynorsk, Occitan, OromoWestCentral, Papiamento, Polish, Portuguese, Romanian, Rundi, Sango, Sardinian, Sepedi, Sesotho, Shona, Sicilian, Silesian, Slovak, Slovene, Somali, Spanish, Sundanese, Swahili, Swati, Swedish, Tagalog, TamasheqLatin, TatarCrimean, TokPisin, Tsonga, Tswana, Tumbuka, Turkish, Turkmen, Twi, Umbundu, UzbekNorthern, Venetian, Vietnamese, Waray, Welsh, Wolof, Xhosa, Yoruba, Zulu)),
    case(Estonian, "päralt", ahashset!(Afrikaans, AymaraCentral, DinkaSouthwestern, Dutch, Estonian, Finnish, German, Limburgish, Luxembourgish, Slovak, Swedish, Turkmen)),
    case(Estonian, "tõeliseks", ahashset!(Estonian, Guarani, Kabuverdianu, Portuguese, Vietnamese)),
    case(French, "contrôle", ahashset!(Acehnese, Afrikaans, Bambara, French, Friulian, Limburgish, Portuguese, Sepedi, Slovak, Vietnamese, Welsh)),
    case(French, "façonnage", ahashset!(AlbanianTosk, AzerbaijaniNorth, Basque, Bokmal, Bosnian, Catalan, French, Friulian, Kabuverdianu, KurdishNorthern, Ligurian, Occitan, Portuguese, TatarCrimean, Turkish, Turkmen, Venetian)),
    case(French, "forêt", ahashset!(Afrikaans, French, Friulian, Kabuverdianu, KurdishNorthern, Portuguese, Sepedi, Welsh)),
    case(French, "où", ahashset!(Czech, Fon, French, Friulian, GaelicScottish, Italian, Limburgish, Lombard, Sardinian, Sicilian, Venetian, Vietnamese, Welsh, Yoruba)),
    case(French, "succèdent", ahashset!(Acehnese, Afrikaans, Catalan, CreoleHaitian, Czech, Dutch, Fon, French, Friulian, GaelicScottish, Italian, Limburgish, Lombard, Occitan, Papiamento, Sardinian, Sesotho, Sicilian, Venetian, Vietnamese, Welsh)),
    case(German, "höher", ahashset!(Acehnese, Afrikaans, AymaraCentral, AzerbaijaniNorth, DinkaSouthwestern, Dutch, Estonian, Finnish, German, Hungarian, Icelandic, Limburgish, Luxembourgish, Swedish, TatarCrimean, Turkish, Turkmen)),
    case(German, "überrascht", ahashset!(Afrikaans, Asturian, AymaraCentral, AzerbaijaniNorth, Catalan, Dutch, French, German, Hungarian, Limburgish, Luxembourgish, Papiamento, Portuguese, Spanish, TatarCrimean, Turkish, Welsh)),
    case(Hawaiian, "pu'u'ō'ō", ahashset!(Hawaiian, Sesotho)),
    case(Hebrew, "בתחרויות", ahashset!(YiddishEastern, Yiddish, Hebrew)),
    case(Icelandic, "minjaverðir", ahashset!(Faroese, Icelandic)),
    case(Italian, "venerdì", ahashset!(Czech, Fon, Friulian, Italian, Limburgish, Lombard, Sardinian, Sicilian, Venetian, Vietnamese)),
    case(Kazakh, "әлем", ahashset!(Bashkir, Kazakh, Tatar)),
    case(Kazakh, "оның", ahashset!(Bashkir, Kazakh, Kyrgyz, Tatar)),
    case(Kazakh, "шаруашылығы", ahashset!(Bashkir, Kazakh)),
    case(Latvian, "aizklātā", ahashset!(Latgalian, Latin, Latvian)),
    case(Latvian, "blaķene", ahashset!(Latgalian, Latvian)),
    case(Latvian, "ceļojumiem", ahashset!(Latgalian, Latvian)),
    case(Latvian, "labāk", ahashset!(Latgalian, Latin, Latvian, Yoruba)),
    case(Latvian, "nebūtu", ahashset!(Latgalian, Latin, Latvian, Lithuanian, Yoruba)),
    case(Latvian, "numuriņu", ahashset!(Latgalian, Latvian)),
    case(Latvian, "palīdzi", ahashset!(Latgalian, Latin, Latvian)),
    case(Latvian, "sistēmas", ahashset!(Latgalian, Latin, Latvian, Sesotho, Yoruba)),
    case(Latvian, "teoloģiska", ahashset!(Latgalian, Latvian)),
    case(Latvian, "viņiem", ahashset!(Latgalian, Latvian)),
    case(Lithuanian, "nebūsime", ahashset!(Latgalian, Latin, Latvian, Lithuanian, Yoruba)),
    case(Macedonian, "затоплување", ahashset!(Macedonian, Serbian)),
    case(Macedonian, "ѕидови", ahashset!(Macedonian, OldChurchSlavonic)),
    case(Macedonian, "набљудувач", ahashset!(Macedonian, Serbian)),
    case(Macedonian, "ректасцензија", ahashset!(Macedonian, Serbian)),
    case(Macedonian, "џамиите", ahashset!(Macedonian, Serbian)),
    case(Marathi, "मिळते", ahashset!(Awadhi, Bhojpuri, Chhattisgarhi, DogriDevanagari, Hindi, KashmiriDevanagari, Magahi, Maithili, Marathi, Nepali, Sanskrit, SindhiDevanagari)),
    case(MongolianHalh, "дөхөж", ahashset!(Bashkir, Kazakh, Kyrgyz, MongolianHalh, Tatar)),
    case(MongolianHalh, "үндсэн", ahashset!(Bashkir, Kazakh, Kyrgyz, MongolianHalh, Tatar)),
    case(Polish, "kradzieżami", ahashset!(Maltese, Polish)),
    case(Polish, "zmieniły", ahashset!(Polish, Silesian)),
    case(Portuguese, "catedráticos", ahashset!(Afrikaans, Asturian, AymaraCentral, Basque, Czech, Dutch, Fon, Galician, Guarani, Hungarian, Igbo, Irish, Kabuverdianu, Limburgish, Lombard, Occitan, Papiamento, Portuguese, Shona, Slovak, Spanish, Vietnamese, Welsh)),
    case(Portuguese, "música", ahashset!(Afrikaans, Asturian, AymaraCentral, Catalan, Czech, Fon, Galician, Guarani, Hungarian, Igbo, Irish, Italian, Kabuverdianu, Kikuyu, Kinyarwanda, Limburgish, Lombard, Occitan, Papiamento, Portuguese, Sardinian, Shona, Slovak, Spanish, Vietnamese, Welsh)),
    case(Portuguese, "política", ahashset!(Afrikaans, Asturian, AymaraCentral, Catalan, Czech, Fon, Galician, Guarani, Hungarian, Igbo, Irish, Italian, Kabuverdianu, Kikuyu, Kinyarwanda, Limburgish, Lombard, Occitan, Portuguese, Sardinian, Shona, Slovak, Spanish, Vietnamese, Welsh)),
    case(Portuguese, "visão", ahashset!(Ewe, Guarani, Portuguese, Vietnamese)),
    case(Romanian, "afişate", ahashset!(AzerbaijaniNorth, KurdishNorthern, Romanian, TatarCrimean, Turkish)),
    case(Romanian, "înviat", ahashset!(Afrikaans, French, Friulian, Guarani, KurdishNorthern, Limburgish, Romanian, Turkish)),
    case(Romanian, "pregătire", ahashset!(Romanian, Vietnamese)),
    case(Russian, "огнём", ahashset!(Bashkir, Belarusian, Kazakh, Kyrgyz, MongolianHalh, Russian, Tajik, Tatar)),
    case(Russian, "сопротивление", ahashset!(Bashkir, Bulgarian, Kazakh, Kyrgyz, Macedonian, MongolianHalh, Russian, Serbian, Tajik, Tatar, Ukrainian)),
    case(Russian, "этот", ahashset!(Bashkir, Belarusian, Kazakh, Kyrgyz, MongolianHalh, Russian, Tajik, Tatar)),
    case(Slovak, "rozohňuje", ahashset!(Czech, Silesian, Slovak)),
    case(Spanish, "años", ahashset!(Asturian, AymaraCentral, Basque, Galician, Guarani, Ilocano, Papiamento, Spanish, Waray, Wolof)),
    case(Ukrainian, "пристрої", ahashset!(OldChurchSlavonic, Ukrainian)),
    case(Vietnamese, "chọn", ahashset!(Igbo, Vietnamese)),
    case(Vietnamese, "cũng", ahashset!(Guarani, Vietnamese)),
    case(Vietnamese, "dụng", ahashset!(Igbo, Vietnamese)),
    case(Vietnamese, "kẽm", ahashset!(Ewe, Guarani, Vietnamese)),
    case(Vietnamese, "mỹ", ahashset!(Guarani, Vietnamese)),
    case(Vietnamese, "nhẹn", ahashset!(Vietnamese, Yoruba)),
    case(Vietnamese, "ravị", ahashset!(Igbo, Vietnamese)),
    case(Vietnamese, "trĩ", ahashset!(Ewe, Guarani, Vietnamese)),
)]
fn test_word_multiple_langs(
    expected_language: Language,
    word: &str,
    expected_languages: AHashSet<Language>,
) {
    let found_words: Vec<_> = alphabet_detector::from_ch_iter(word.char_indices()).collect();
    if found_words.len() > 1 {
        panic!("Not a word '{}' got {:?}", word, found_words);
    }
    let languages = langs_count_max(found_words[0].langs_cnt).0;

    assert!(
        languages.contains(&expected_language),
        "{:?} word '{}', got {:?}",
        expected_language,
        word,
        languages
    );
    assert_eq!(
        languages, expected_languages,
        "{:?} word '{}'",
        expected_language, word
    );
}
